epi_r <- read.csv("D:/kamagyana/Computing/DARET/Assignments/epi_r.csv")
View(epi_r)
save.image("D:/kamagyana/Computing/DARET/R-code-submissions/Asst21.1.RData")
str(epi_r)
epi_r$title <- as.character(epi_r$title)
class(epi_r$title)
head(epi_r)
sum(is.na(epi_r))
library(mice)
numepi_r <- epi_r[,-1]
ncol(numepi_r)
colnames(numepi_r)
summary(numepi_r[,c(1,2,3,4,5,6,7,8,9,10)])
cpfs <- numepi_r[,c(2,3,4,5)]
class(cpfs)
nrow(cpfs)
nrow(numepi_r)
sum(is.na(cpfs))
tempData <- mice(cpfs,m=3,maxit=25,method='pmm',seed=500)
compcpfs <- complete(tempData,1)
sum(is.na(compcpfs))
numepi_r[,c(2,3,4,5)] <- compcpfs[,c(1,2,3,4)]
sum(is.na(numepi_r[,c(2,3,4,5)]))
ncol(numepi_r)
sum(is.na(numepi_r))
install.packages("factoextra")
library(factoextra)
res.pca <- prcomp(numepi_r, scale = TRUE)
res.pca
summary(res.pca)
colnames(res.pca)
str(res.pca)
POV <- res.pca$sdev^2 / sum(res.pca$sdev^2)
POV
fivz_eig(res.pca)
fviz_eig(res.pca)
eig_val <- get_eigenvalue(res.pca)
eig_val
fviz_pca_ind(res.pca,col.ind="cos2",gradient.cols = c("#00AFBB","#E7B800","#FC4E07"),repel = TRUE)
fviz_pca_var(res.pca,col.ind="contrib",gradient.cols = c("#00AFBB","#E7B800","#FC4E07"),repel = TRUE)
fviz_pca_biplot(res.pca, repel = TRUE, col.var = "#2E9FDF", col.in = "#696969")